import { MonitoringDevice, MonitoringAlert, MonitoringStats } from '@domain/entities/monitoring';
import { MonitoringRepository } from '@domain/ports/MonitoringRepository';

const SEED_DEVICES: MonitoringDevice[] = [
  {
    id: 'dev-1',
    name: 'NAS-Central-01',
    type: 'nas',
    ipAddress: '192.168.1.1',
    status: 'online',
    coordinates: { lat: -34.603, lng: -58.381 },
    nasId: 'nas-1',
    clientId: null,
    clientName: null,
    lastSeen: new Date(Date.now() - 60_000).toISOString(),
    uptimePercent: 99.9,
    latency: 2,
    downloadMbps: 100,
    uploadMbps: 50,
    alertCount: 0,
  },
  {
    id: 'dev-2',
    name: 'NAS-Norte-02',
    type: 'nas',
    ipAddress: '192.168.1.2',
    status: 'online',
    coordinates: { lat: -34.580, lng: -58.420 },
    nasId: 'nas-2',
    clientId: null,
    clientName: null,
    lastSeen: new Date(Date.now() - 120_000).toISOString(),
    uptimePercent: 98.5,
    latency: 5,
    downloadMbps: 80,
    uploadMbps: 40,
    alertCount: 0,
  },
  {
    id: 'dev-3',
    name: 'CPE-Cliente-Rodriguez',
    type: 'cpe',
    ipAddress: '10.0.0.10',
    status: 'online',
    coordinates: { lat: -34.615, lng: -58.395 },
    nasId: 'nas-1',
    clientId: 'client-42',
    clientName: 'Carlos Rodríguez',
    lastSeen: new Date(Date.now() - 30_000).toISOString(),
    uptimePercent: 97.2,
    latency: 12,
    downloadMbps: 50,
    uploadMbps: 25,
    alertCount: 0,
  },
  {
    id: 'dev-4',
    name: 'Sitio-Palermo',
    type: 'site',
    ipAddress: '172.16.0.1',
    status: 'online',
    coordinates: { lat: -34.590, lng: -58.430 },
    nasId: null,
    clientId: null,
    clientName: null,
    lastSeen: new Date(Date.now() - 45_000).toISOString(),
    uptimePercent: 99.1,
    latency: 3,
    downloadMbps: 200,
    uploadMbps: 100,
    alertCount: 0,
  },
  {
    id: 'dev-5',
    name: 'ONU-Belgrano-01',
    type: 'onu',
    ipAddress: '10.0.1.1',
    status: 'online',
    coordinates: { lat: -34.560, lng: -58.460 },
    nasId: 'nas-2',
    clientId: null,
    clientName: null,
    lastSeen: new Date(Date.now() - 90_000).toISOString(),
    uptimePercent: 99.8,
    latency: 1,
    downloadMbps: 1000,
    uploadMbps: 500,
    alertCount: 0,
  },
  {
    id: 'dev-6',
    name: 'CPE-Cliente-Torres',
    type: 'cpe',
    ipAddress: '10.0.0.20',
    status: 'offline',
    coordinates: { lat: -34.630, lng: -58.370 },
    nasId: 'nas-1',
    clientId: 'client-15',
    clientName: 'Ana Torres',
    lastSeen: new Date(Date.now() - 3_600_000).toISOString(),
    uptimePercent: 72.3,
    latency: null,
    downloadMbps: null,
    uploadMbps: null,
    alertCount: 2,
  },
  {
    id: 'dev-7',
    name: 'CPE-Cliente-Lopez',
    type: 'cpe',
    ipAddress: '10.0.0.30',
    status: 'offline',
    coordinates: { lat: -34.645, lng: -58.410 },
    nasId: 'nas-1',
    clientId: 'client-33',
    clientName: 'Jorge López',
    lastSeen: new Date(Date.now() - 7_200_000).toISOString(),
    uptimePercent: 65.0,
    latency: null,
    downloadMbps: null,
    uploadMbps: null,
    alertCount: 3,
  },
  {
    id: 'dev-8',
    name: 'NAS-Sur-03',
    type: 'nas',
    ipAddress: '192.168.1.3',
    status: 'warning',
    coordinates: { lat: -34.660, lng: -58.350 },
    nasId: 'nas-3',
    clientId: null,
    clientName: null,
    lastSeen: new Date(Date.now() - 180_000).toISOString(),
    uptimePercent: 88.1,
    latency: 85,
    downloadMbps: 60,
    uploadMbps: 30,
    alertCount: 1,
  },
  {
    id: 'dev-9',
    name: 'CPE-Cliente-Garcia',
    type: 'cpe',
    ipAddress: '10.0.0.40',
    status: 'online',
    coordinates: { lat: -34.608, lng: -58.445 },
    nasId: 'nas-2',
    clientId: 'client-7',
    clientName: 'María García',
    lastSeen: new Date(Date.now() - 60_000).toISOString(),
    uptimePercent: 99.5,
    latency: 8,
    downloadMbps: 30,
    uploadMbps: 15,
    alertCount: 0,
  },
  {
    id: 'dev-10',
    name: 'Sitio-Caballito',
    type: 'site',
    ipAddress: '172.16.0.2',
    status: 'online',
    coordinates: { lat: -34.620, lng: -58.440 },
    nasId: null,
    clientId: null,
    clientName: null,
    lastSeen: new Date(Date.now() - 30_000).toISOString(),
    uptimePercent: 99.7,
    latency: 2,
    downloadMbps: 150,
    uploadMbps: 75,
    alertCount: 0,
  },
  {
    id: 'dev-11',
    name: 'ONU-Flores-02',
    type: 'onu',
    ipAddress: '10.0.1.2',
    status: 'online',
    coordinates: { lat: -34.635, lng: -58.465 },
    nasId: 'nas-3',
    clientId: null,
    clientName: null,
    lastSeen: new Date(Date.now() - 60_000).toISOString(),
    uptimePercent: 98.9,
    latency: 1,
    downloadMbps: 1000,
    uploadMbps: 500,
    alertCount: 0,
  },
  {
    id: 'dev-12',
    name: 'CPE-Cliente-Fernandez',
    type: 'cpe',
    ipAddress: '10.0.0.50',
    status: 'online',
    coordinates: { lat: -34.598, lng: -58.408 },
    nasId: 'nas-1',
    clientId: 'client-22',
    clientName: 'Luis Fernández',
    lastSeen: new Date(Date.now() - 90_000).toISOString(),
    uptimePercent: 96.8,
    latency: 15,
    downloadMbps: 50,
    uploadMbps: 25,
    alertCount: 0,
  },
  {
    id: 'dev-13',
    name: 'NAS-Oeste-04',
    type: 'nas',
    ipAddress: '192.168.1.4',
    status: 'online',
    coordinates: { lat: -34.640, lng: -58.490 },
    nasId: 'nas-4',
    clientId: null,
    clientName: null,
    lastSeen: new Date(Date.now() - 60_000).toISOString(),
    uptimePercent: 99.3,
    latency: 4,
    downloadMbps: 90,
    uploadMbps: 45,
    alertCount: 0,
  },
  {
    id: 'dev-14',
    name: 'CPE-Cliente-Martinez',
    type: 'cpe',
    ipAddress: '10.0.0.60',
    status: 'offline',
    coordinates: { lat: -34.655, lng: -58.480 },
    nasId: 'nas-4',
    clientId: 'client-55',
    clientName: 'Pedro Martínez',
    lastSeen: new Date(Date.now() - 5_400_000).toISOString(),
    uptimePercent: 58.4,
    latency: null,
    downloadMbps: null,
    uploadMbps: null,
    alertCount: 2,
  },
  {
    id: 'dev-15',
    name: 'Sitio-Liniers',
    type: 'site',
    ipAddress: '172.16.0.3',
    status: 'warning',
    coordinates: { lat: -34.648, lng: -58.502 },
    nasId: null,
    clientId: null,
    clientName: null,
    lastSeen: new Date(Date.now() - 300_000).toISOString(),
    uptimePercent: 82.6,
    latency: 120,
    downloadMbps: 40,
    uploadMbps: 20,
    alertCount: 1,
  },
];

const SEED_ALERTS: MonitoringAlert[] = [
  {
    id: 'alert-1',
    deviceId: 'dev-6',
    deviceName: 'CPE-Cliente-Torres',
    type: 'offline',
    severity: 'critical',
    message: 'Dispositivo sin respuesta por más de 1 hora',
    occurredAt: new Date(Date.now() - 3_600_000).toISOString(),
    resolvedAt: null,
    acknowledged: false,
  },
  {
    id: 'alert-2',
    deviceId: 'dev-7',
    deviceName: 'CPE-Cliente-Lopez',
    type: 'offline',
    severity: 'critical',
    message: 'Dispositivo sin respuesta por más de 2 horas',
    occurredAt: new Date(Date.now() - 7_200_000).toISOString(),
    resolvedAt: null,
    acknowledged: false,
  },
  {
    id: 'alert-3',
    deviceId: 'dev-8',
    deviceName: 'NAS-Sur-03',
    type: 'high_latency',
    severity: 'warning',
    message: 'Latencia elevada: 85ms (umbral: 50ms)',
    occurredAt: new Date(Date.now() - 900_000).toISOString(),
    resolvedAt: null,
    acknowledged: false,
  },
  {
    id: 'alert-4',
    deviceId: 'dev-14',
    deviceName: 'CPE-Cliente-Martinez',
    type: 'offline',
    severity: 'critical',
    message: 'Dispositivo sin respuesta por más de 90 minutos',
    occurredAt: new Date(Date.now() - 5_400_000).toISOString(),
    resolvedAt: null,
    acknowledged: true,
  },
  {
    id: 'alert-5',
    deviceId: 'dev-15',
    deviceName: 'Sitio-Liniers',
    type: 'high_latency',
    severity: 'warning',
    message: 'Latencia elevada: 120ms (umbral: 50ms)',
    occurredAt: new Date(Date.now() - 1_800_000).toISOString(),
    resolvedAt: null,
    acknowledged: false,
  },
  {
    id: 'alert-6',
    deviceId: 'dev-3',
    deviceName: 'CPE-Cliente-Rodriguez',
    type: 'packet_loss',
    severity: 'info',
    message: 'Pérdida de paquetes detectada: 2%',
    occurredAt: new Date(Date.now() - 600_000).toISOString(),
    resolvedAt: null,
    acknowledged: true,
  },
  {
    id: 'alert-7',
    deviceId: 'dev-4',
    deviceName: 'Sitio-Palermo',
    type: 'bandwidth_exceeded',
    severity: 'warning',
    message: 'Ancho de banda al 95% de capacidad',
    occurredAt: new Date(Date.now() - 300_000).toISOString(),
    resolvedAt: null,
    acknowledged: false,
  },
  {
    id: 'alert-8',
    deviceId: 'dev-1',
    deviceName: 'NAS-Central-01',
    type: 'config_changed',
    severity: 'info',
    message: 'Configuración modificada por admin',
    occurredAt: new Date(Date.now() - 86_400_000).toISOString(),
    resolvedAt: new Date(Date.now() - 86_000_000).toISOString(),
    acknowledged: true,
  },
];

export class InMemoryMonitoringRepository implements MonitoringRepository {
  private devices: MonitoringDevice[] = SEED_DEVICES.map(d => ({ ...d }));
  private alerts: MonitoringAlert[] = SEED_ALERTS.map(a => ({ ...a }));

  async getStats(): Promise<MonitoringStats> {
    const online = this.devices.filter(d => d.status === 'online').length;
    const offline = this.devices.filter(d => d.status === 'offline').length;
    const warning = this.devices.filter(d => d.status === 'warning').length;
    const activeAlerts = this.alerts.filter(a => a.resolvedAt === null).length;
    const criticalAlerts = this.alerts.filter(a => a.severity === 'critical' && a.resolvedAt === null).length;
    const devicesWithLatency = this.devices.filter(d => d.latency !== null);
    const avgLatency = devicesWithLatency.length > 0
      ? devicesWithLatency.reduce((sum, d) => sum + (d.latency ?? 0), 0) / devicesWithLatency.length
      : 0;
    const avgUptimePercent = this.devices.reduce((sum, d) => sum + d.uptimePercent, 0) / this.devices.length;

    return {
      totalDevices: this.devices.length,
      onlineDevices: online,
      offlineDevices: offline,
      warningDevices: warning,
      activeAlerts,
      criticalAlerts,
      avgLatency: Math.round(avgLatency * 10) / 10,
      avgUptimePercent: Math.round(avgUptimePercent * 10) / 10,
    };
  }

  async findAllDevices(): Promise<MonitoringDevice[]> {
    return [...this.devices];
  }

  async findAllAlerts(): Promise<MonitoringAlert[]> {
    return [...this.alerts];
  }

  async acknowledgeAlert(id: string): Promise<MonitoringAlert | null> {
    const index = this.alerts.findIndex(a => a.id === id);
    if (index === -1) return null;
    this.alerts[index] = { ...this.alerts[index], acknowledged: true };
    return this.alerts[index];
  }
}
