/**
 * Gigared password policy (#47h).
 *
 * Gigared's register endpoint rejects any character outside [a-z0-9]
 * ("La password solo puede contener letras minusculas y numeros"). The previous
 * server-side generator used randomBytes(...).toString('base64url'), which emits
 * uppercase letters plus '-'/'_' — every register with an autogenerated password
 * was rejected upstream.
 *
 * Policy:
 *  - alphabet: [a-z0-9] (36 symbols)
 *  - generated length: 12
 *  - caller-provided passwords: 8..64 chars, same alphabet
 *  - cryptographically random: crypto.randomInt (rejection sampling, unbiased) —
 *    never Math.random.
 *
 * The password is transit-only: forwarded to Gigared, never persisted, logged, or returned.
 */
import { randomInt } from 'crypto';

const ALPHABET = 'abcdefghijklmnopqrstuvwxyz0123456789';
const GENERATED_LENGTH = 12;
const MIN_LENGTH = 8;
const MAX_LENGTH = 64;

/** Matches a non-empty string of lowercase letters and digits only. */
export const GIGARED_PASSWORD_RE = /^[a-z0-9]+$/;

/**
 * Generate a Gigared-compliant password: 12 chars, all in [a-z0-9],
 * cryptographically random (randomInt → uniform, unbiased).
 */
export function generateGigaredPassword(): string {
  let out = '';
  for (let i = 0; i < GENERATED_LENGTH; i++) {
    out += ALPHABET[randomInt(ALPHABET.length)];
  }
  return out;
}

/**
 * Validate a caller-provided password against the Gigared policy:
 * lowercase letters + digits only, length 8..64.
 */
export function isValidGigaredPassword(value: string): boolean {
  if (value.length < MIN_LENGTH || value.length > MAX_LENGTH) return false;
  return GIGARED_PASSWORD_RE.test(value);
}
